### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by MarcelWildenburg** [Devoxx4Kids-NPO/littil-frontend#105]
On the staging environment it is not possible to register a new account.

A XMLHttpRequest is blocked by CORS policy.
Access to XMLHttpRequest at 'https://api.staging.littil.org/api/v1/users/user' from origin 'https://staging.littil.org/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by LDMGN** [comment]
This is a back-end issue. It has probably been fixed in the latest commit of the LITTIL-166 branch (of the back-end repo).

**Comment by MarcelWildenburg** [comment]
Issue is fixed in back-end deployment script for infrastructure.
