### ISSUE TITLE
use OpenAPI definitions

### ISSUE THREAD

**Issue by tubbynl** [Devoxx4Kids-NPO/littil-frontend#9]
the back-end will produce OpenAPI specs; use that to generate models (and perhaps services?)

https://github.com/Devoxx4Kids-NPO/littil-backend/pull/47

https://www.kevinboosten.dev/how-i-use-an-openapi-spec-in-my-angular-projects

**Comment by Anjanas-dh** [comment]
Maybe frontend can use the Actions API to retrieve the latest openapi artifact of backend build?
https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28

**Comment by tubbynl** [comment]
Currently implemented with a openapi.json at the root of the project
